### PR TITLE
Parallelize templates cleaning

### PR DESCRIPTION
**Pull request by gcroci2**
With this PR the cleaning of MHCI and MHCII templates is done using parallelization through joblib, with n_jobs=-1 (all CPUs are used).

pMHCI cleaning time with no parallelization: 586 s
pMHCII cleaning time with no parallelization: 132 s
pMHCI cleaning time with -1 jobs: 103 s
pMHCII cleaning time with -1 jobs: 19 s

On my local computer the parallelization reduces timings by ~ 5-6X

### CODE REVIEW

**Comment by DarioMarzella** [comment]
Very nice! Could you please make it in a way that construct_database takes as input the number of cores and passes it on to the cleaning step?
Also, I am quite puzzled by the times, they seem very short to me. Is it possible you try to construct a whole database and see how much time it takes with the cleaning parallelized?

**Comment by gcroci2** [comment]
> Very nice @gcroci2 ! Could you please make it in a way that construct_database takes as input the number of cores and passes it on to the cleaning step? Also, I am quite puzzled by the times, they seem very short to me. Is it possible you try to construct a whole database and see how much time it takes with the cleaning parallelized?

Done, I added n_jobs as a attribute for Database class. It defaults to -1, but users can change it when they instantiate the Database class. 

The code that I ran was 
```
db = Database.Database()
db.construct_database(save='PANDORA_files/data/db.pkl')
```
And I put some time variables in the Database.py file, to save timings in a .txt file. I evaluated exactly both the for cycles to clean templates. They should be representative, at least for my machine (Mac Pro with M1 chip).

**Comment by DarioMarzella** [comment]
For me, running on a Linux cluster node with a Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz, the running time remains quite high even by using 20 cores.
I tried cleaning only one pdb and it takes about 2.5 seconds, but when running in parallel the time scales up to 17 to 33 seconds per pdb. Can there be some I/O problem? Or some file/argument that needs to be unpacked by every process and works as a bottleneck?

**Comment by DarioMarzella** [comment]
Found it.[ Line 1451](https://github.com/X-lab-3D/PANDORA/blob/4d9bb42d4567f69102492f7afb024c9bb4874372/PANDORA/Database/Database_functions.py#L1451), where the pdb gets written, works as a bottleneck and probably does not allow a complete parallelization, as the more parallel processes there are the longer it can take for some structures to be written. 
Now the problem is how to solve it, we still need to write the pdbs.

**Comment by DarioMarzella** [comment]
```get_header_and_remarks``` has now been removed. The template files will not have a full header as loading it is redundant, but they will simply have a link to the original IMGT structure, with all the information.I also fixed the Parallel output that was not properly tunnelled in db.MHC<class>_data

**Comment by DarioMarzella** [comment]
Total time on Linux machine with HDDs reduced from ~2hrs to ~4m, using only 4 cores. I would call this branch a success!

**Pull request merged**
